### PR TITLE
Ovs/db

### PR DESCRIPTION
**Pull request by matbu**

### CODE REVIEW

**Comment by matbu** [comment]
This pull request add the support of non containerized and non standard Openstack services such a OVS in this case.
The config.yaml, file which describes all the services where we want to pull and handle the configuration is now extended with a mapping format.
The hosts key is new as well, which allow os-diff to loop over the different hosts in order to pull configurations for each hosts.
In the case of ovs, it can loop over the nodes and extract the external ids.

A service_command key is added, which the command that can be executed to get the config. It could be a simple cat /etc/something or like ovs case a tool command. The output is stored into a file and used for analyze later.

The config_mapping is the mapping to match OSP/TripleO/Tool config keys with the new Edpm config keys located in the edpm CRs.

If someone wants to add a new non-standard service like this, he will have to simply fill those fields and create the mapping according to the Edpm CRS.
Os-diff build a structure on EDPM CRs so all the keys could be loaded and query.

  ovs_external_ids:
    hosts:
      - standalone
    service_command: "ovs-vsctl list Open  list Open_vSwitch . | grep external_ids | awk -F ': ' '{ print $2; }'"
    cat_output: true
    path:
      - ovs_external_ids.json
    config_mapping:
      ovn-bridge-mappings: edpm_ovn_bridge_mappings
      ovn-bridge: edpm_ovn_bridge
      ovn-encap-type: edpm_ovn_encap_type
      ovn-match-northd-version: ovn_match_northd_version
      ovn-monitor-all: ovn_monitor_all
      ovn-remote-probe-interval: edpm_ovn_remote_probe_interval
      ovn-ofctrl-wait-before-clear: edpm_ovn_ofctrl_wait_before_clear

**Comment by davidjpeacock** [comment]
Still working my way through this Mathieu, thank you :-)

**Review by davidjpeacock — APPROVED** [review]
I suspect this is going to cause my unit tests which were written before this PR are going to be very broken - but let's see!

**Comment by davidjpeacock** [comment]
Needs a rebase @matbu!

**Pull request merged**
